//go:generate go run ../../instruction-gen/main.go ../../instruction-gen/spec.json ./instructions.gen.go
//go:generate go fmt ./instructions.gen.go

// GENERATED FILE - Run "go generate ./..." to update

package emulator

var instructions = []instruction{
	{
		Opcode:   "0x00",
		Mnemonic: "NOP",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x01",
		Mnemonic: "LD16",
		Size:     3,
		Operands: []operand{
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
			{
				Name: "d16",
				Type: operandD16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x02",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(BC)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerBC,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x03",
		Mnemonic: "INC16",
		Size:     1,
		Operands: []operand{
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x04",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x05",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x06",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x07",
		Mnemonic: "RLCA",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x08",
		Mnemonic: "LD8",
		Size:     3,
		Operands: []operand{
			{
				Name: "(a16)",
				Type: operandA16Ptr,
				Ref:  "",
			},
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x09",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x0A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(BC)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x0B",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x0C",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x0D",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x0E",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x0F",
		Mnemonic: "RRCA",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x10",
		Mnemonic: "STOP",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x11",
		Mnemonic: "LD16",
		Size:     3,
		Operands: []operand{
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
			{
				Name: "d16",
				Type: operandD16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x12",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(DE)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerDE,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x13",
		Mnemonic: "INC16",
		Size:     1,
		Operands: []operand{
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x14",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x15",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x16",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x17",
		Mnemonic: "RLA",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x18",
		Mnemonic: "JR",
		Size:     2,
		Operands: []operand{
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x19",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x1A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(DE)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x1B",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x1C",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x1D",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x1E",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x1F",
		Mnemonic: "RRA",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x20",
		Mnemonic: "JR",
		Size:     2,
		Operands: []operand{
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
			{
				Name:          "NZ",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagZ,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x21",
		Mnemonic: "LD16",
		Size:     3,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name: "d16",
				Type: operandD16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x22",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:           "(HL+)",
				Type:           operandReg16Ptr,
				Ref:            "",
				RefRegister16:  registerHL,
				IncrementReg16: true,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x23",
		Mnemonic: "INC16",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x24",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x25",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x26",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x27",
		Mnemonic: "DAA",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "Z",
			N: "-",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x28",
		Mnemonic: "JR",
		Size:     2,
		Operands: []operand{
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
			{
				Name:    "Z",
				Type:    operandFlag,
				Ref:     "",
				RefFlag: flagZ,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x29",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x2A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:           "(HL+)",
				Type:           operandReg16Ptr,
				Ref:            "",
				RefRegister16:  registerHL,
				IncrementReg16: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x2B",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x2C",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x2D",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x2E",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x2F",
		Mnemonic: "CPL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "1",
			H: "1",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x30",
		Mnemonic: "JR",
		Size:     2,
		Operands: []operand{
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
			{
				Name:          "NC",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagC,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x31",
		Mnemonic: "LD16",
		Size:     3,
		Operands: []operand{
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
			{
				Name: "d16",
				Type: operandD16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x32",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:           "(HL-)",
				Type:           operandReg16Ptr,
				Ref:            "",
				RefRegister16:  registerHL,
				DecrementReg16: true,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x33",
		Mnemonic: "INC16",
		Size:     1,
		Operands: []operand{
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x34",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x35",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x36",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x37",
		Mnemonic: "SCF",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "0",
			C: "1",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x38",
		Mnemonic: "JR",
		Size:     2,
		Operands: []operand{
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x39",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
		},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x3A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:           "(HL-)",
				Type:           operandReg16Ptr,
				Ref:            "",
				RefRegister16:  registerHL,
				DecrementReg16: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x3B",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x3C",
		Mnemonic: "INC8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x3D",
		Mnemonic: "DEC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "-",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x3E",
		Mnemonic: "LD8",
		Size:     2,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x3F",
		Mnemonic: "CCF",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "0",
			H: "0",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x40",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x41",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x42",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x43",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x44",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x45",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x46",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x47",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x48",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x49",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4B",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4C",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4D",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4E",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x4F",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x50",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x51",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x52",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x53",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x54",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x55",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x56",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x57",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x58",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x59",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5B",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5C",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5D",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5E",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x5F",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x60",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x61",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x62",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x63",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x64",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x65",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x66",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x67",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x68",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x69",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6B",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6C",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6D",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6E",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x6F",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x70",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x71",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x72",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x73",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x74",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x75",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x76",
		Mnemonic: "HALT",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x77",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x78",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x79",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7A",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7B",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7C",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7D",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7E",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x7F",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0x80",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x81",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x82",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x83",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x84",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x85",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x86",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x87",
		Mnemonic: "ADD",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x88",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x89",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8A",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8B",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8C",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8D",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8E",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x8F",
		Mnemonic: "ADC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x90",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x91",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x92",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x93",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x94",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x95",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x96",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x97",
		Mnemonic: "SUB",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x98",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x99",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9A",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9B",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9C",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9D",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9E",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0x9F",
		Mnemonic: "SBC",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA0",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA1",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA2",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA3",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA4",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA5",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA6",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA7",
		Mnemonic: "AND",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA8",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xA9",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAA",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAB",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAC",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAD",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAE",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xAF",
		Mnemonic: "XOR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB0",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB1",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB2",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB3",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB4",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB5",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB6",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB7",
		Mnemonic: "OR",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB8",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "B",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerB,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xB9",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBA",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "D",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerD,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBB",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "E",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerE,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBC",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "H",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerH,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBD",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "L",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBE",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "(HL)",
				Type:          operandReg16Ptr,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xBF",
		Mnemonic: "CP",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xC0",
		Mnemonic: "RET",
		Size:     1,
		Operands: []operand{
			{
				Name:          "NZ",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagZ,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC1",
		Mnemonic: "POP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC2",
		Mnemonic: "JP",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
			{
				Name:          "NZ",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagZ,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC3",
		Mnemonic: "JP",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC4",
		Mnemonic: "CALL",
		Size:     3,
		Operands: []operand{
			{
				Name:          "NZ",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagZ,
				RefFlagNegate: true,
			},
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC5",
		Mnemonic: "PUSH",
		Size:     1,
		Operands: []operand{
			{
				Name:          "BC",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerBC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC6",
		Mnemonic: "ADD",
		Size:     2,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xC7",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "00H",
				Type: operandHex,
				Ref:  "00H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC8",
		Mnemonic: "RET",
		Size:     1,
		Operands: []operand{
			{
				Name:    "Z",
				Type:    operandFlag,
				Ref:     "",
				RefFlag: flagZ,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xC9",
		Mnemonic: "RET",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xCA",
		Mnemonic: "JP",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
			{
				Name:    "Z",
				Type:    operandFlag,
				Ref:     "",
				RefFlag: flagZ,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xCB",
		Mnemonic: "PREFIX",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xCC",
		Mnemonic: "CALL",
		Size:     3,
		Operands: []operand{
			{
				Name:    "Z",
				Type:    operandFlag,
				Ref:     "",
				RefFlag: flagZ,
			},
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xCD",
		Mnemonic: "CALL",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xCE",
		Mnemonic: "ADC",
		Size:     2,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xCF",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "08H",
				Type: operandHex,
				Ref:  "08H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD0",
		Mnemonic: "RET",
		Size:     1,
		Operands: []operand{
			{
				Name:          "NC",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagC,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD1",
		Mnemonic: "POP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD2",
		Mnemonic: "JP",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
			{
				Name:          "NC",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagC,
				RefFlagNegate: true,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD3",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD4",
		Mnemonic: "CALL",
		Size:     3,
		Operands: []operand{
			{
				Name:          "NC",
				Type:          operandFlag,
				Ref:           "",
				RefFlag:       flagC,
				RefFlagNegate: true,
			},
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD5",
		Mnemonic: "PUSH",
		Size:     1,
		Operands: []operand{
			{
				Name:          "DE",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerDE,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD6",
		Mnemonic: "SUB",
		Size:     2,
		Operands: []operand{
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xD7",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "10H",
				Type: operandHex,
				Ref:  "10H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD8",
		Mnemonic: "RET",
		Size:     1,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xD9",
		Mnemonic: "RETI",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xDA",
		Mnemonic: "JP",
		Size:     3,
		Operands: []operand{
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xDB",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xDC",
		Mnemonic: "CALL",
		Size:     3,
		Operands: []operand{
			{
				Name:         "C",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name: "a16",
				Type: operandA16,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xDD",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xDE",
		Mnemonic: "SBC",
		Size:     2,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xDF",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "18H",
				Type: operandHex,
				Ref:  "18H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE0",
		Mnemonic: "LDH",
		Size:     2,
		Operands: []operand{
			{
				Name: "(a8)",
				Type: operandA8Ptr,
				Ref:  "",
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE1",
		Mnemonic: "POP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE2",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "(C)",
				Type:         operandReg8Ptr,
				Ref:          "",
				RefRegister8: registerC,
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE3",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE4",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE5",
		Mnemonic: "PUSH",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE6",
		Mnemonic: "AND",
		Size:     2,
		Operands: []operand{
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "1",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xE7",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "20H",
				Type: operandHex,
				Ref:  "20H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xE8",
		Mnemonic: "ADD",
		Size:     2,
		Operands: []operand{
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
			{
				Name: "r8",
				Type: operandR8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xE9",
		Mnemonic: "JP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xEA",
		Mnemonic: "LD8",
		Size:     3,
		Operands: []operand{
			{
				Name: "(a16)",
				Type: operandA16Ptr,
				Ref:  "",
			},
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xEB",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xEC",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xED",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xEE",
		Mnemonic: "XOR",
		Size:     2,
		Operands: []operand{
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xEF",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "28H",
				Type: operandHex,
				Ref:  "28H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF0",
		Mnemonic: "LDH",
		Size:     2,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "(a8)",
				Type: operandA8Ptr,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF1",
		Mnemonic: "POP",
		Size:     1,
		Operands: []operand{
			{
				Name:          "AF",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerAF,
			},
		},
		Flags: flags{
			Z: "Z",
			N: "N",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xF2",
		Mnemonic: "LD8",
		Size:     1,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name:         "(C)",
				Type:         operandReg8Ptr,
				Ref:          "",
				RefRegister8: registerC,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF3",
		Mnemonic: "DI",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF4",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF5",
		Mnemonic: "PUSH",
		Size:     1,
		Operands: []operand{
			{
				Name:          "AF",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerAF,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF6",
		Mnemonic: "OR",
		Size:     2,
		Operands: []operand{
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "0",
			H: "0",
			C: "0",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xF7",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "30H",
				Type: operandHex,
				Ref:  "30H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xF8",
		Mnemonic: "LD16",
		Size:     2,
		Operands: []operand{
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
			{
				Name:           "SP+",
				Type:           operandReg16,
				Ref:            "",
				RefRegister16:  registerSP,
				IncrementReg16: true,
			},
		},
		Flags: flags{
			Z: "0",
			N: "0",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xF9",
		Mnemonic: "LD16",
		Size:     1,
		Operands: []operand{
			{
				Name:          "SP",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerSP,
			},
			{
				Name:          "HL",
				Type:          operandReg16,
				Ref:           "",
				RefRegister16: registerHL,
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xFA",
		Mnemonic: "LD8",
		Size:     3,
		Operands: []operand{
			{
				Name:         "A",
				Type:         operandReg8,
				Ref:          "",
				RefRegister8: registerA,
			},
			{
				Name: "(a16)",
				Type: operandA16Ptr,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xFB",
		Mnemonic: "EI",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xFC",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xFD",
		Mnemonic: "ILLEGAL",
		Size:     1,
		Operands: []operand{},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
	{
		Opcode:   "0xFE",
		Mnemonic: "CP",
		Size:     2,
		Operands: []operand{
			{
				Name: "d8",
				Type: operandD8,
				Ref:  "",
			},
		},
		Flags: flags{
			Z: "Z",
			N: "1",
			H: "H",
			C: "C",
		},
		Todo: "mutates flags",
	},
	{
		Opcode:   "0xFF",
		Mnemonic: "RST",
		Size:     1,
		Operands: []operand{
			{
				Name: "38H",
				Type: operandHex,
				Ref:  "38H",
			},
		},
		Flags: flags{
			Z: "-",
			N: "-",
			H: "-",
			C: "-",
		},
		Todo: "",
	},
}
